[workspace]
authors = ["nandi <nandithebull@outlook.com>"]
channels = ["https://repo.prefix.dev/nandi-testing", "conda-forge"]
name = "syncer"
platforms = ["linux-64"]
version = "0.1.0"

[tasks.start]
cmd = "PYTHONPATH=$PYTHONPATH:/usr/lib/python3.14/site-packages python syncer.py"

[dependencies]
paramiko = ">=4.0.0,<5"
